# Site settings
baseurl = "antonioluppi.github.io" #without ending slash
languageCode = "en-us"
title = "Antonio Luppi"
theme = "hugo-identity-theme"
#themesDir = "../.."

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-XXXXX-Y"

[params]
  
  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance
  
  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Antonio Carlos Luppi Júnior"
    # Avatars can be written to images/avatars/
    avatar = "avatar.jpg"
    position = "Electrical Engineer"
    livesIn = "[Florianópolis, Brazil](#some-maps-url)"
    scope = [
        "[Freelancer Hardware Engineer](antonioluppi.wordpress.com)",
       "and [fitness nerd blogger](aprendacalistenia.wordpress.com) in the free time",
      # "and OSH advocate and board member of [Tarrafa Hacker Club](tarrafa.net)",
      ]
  #  biography = """Jane Powers is plain awesome. He worked at Corp A and B and is open for new work.  Even new lines and other markdown styles are working within the bio."""



  # Contact form settings
    
  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "your@email.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = false
    title = "Touch Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting us."
    error = "Message could not be send. Please contact us at "

    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://instagram.com/antonioluppi"

  [[params.social]]
    title = "Portfolio & Blog"
    icon = "fa-wordpress"
    link = "https://antonioluppi.wordpress.com"
    
  [[params.social]]
	title= "github"
	 icon = "fa-github"
	 link = "https://github.com/antonioluppi"

  [[params.social]]
	title= "linkedin"
	icon = "fa-linkedin"
	link = "https://br.linkedin.com/in/antonioluppi"

  [[params.social]]
    title = "My other blog in calisthenics [pt-br]"
    icon = "fa-wordpress"
    link = "https://aprendacalistenia.wordpress.com"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
      copyright = "Antonio Carlos Luppi Júnior"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
